/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as BSplatRouteImport } from './routes/b.$'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CookbookIndexRouteImport } from './routes/cookbook.index'
import { Route as CookbookRecipeRouteImport } from './routes/cookbook.$recipe'
import { Route as McpIndexRouteImport } from './routes/mcp.index'
import { Route as McpClientRouteImport } from './routes/mcp.$client'
import { Route as ApiDataCapabilityRouteImport } from './routes/api.data.$capability'
import { Route as ProjectsSlugIndexRouteImport } from './routes/projects.$slug.index'
import { Route as ProjectsSlugTopicRouteImport } from './routes/projects.$slug.$topic'
import { Route as ProjectsSlugThisWeekRouteImport } from './routes/projects.$slug.this-week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BSplatRoute = BSplatRouteImport.update({
  id: '/b/$',
  path: '/b/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/cookbook/',
  path: '/cookbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRecipeRoute = CookbookRecipeRouteImport.update({
  id: '/cookbook/$recipe',
  path: '/cookbook/$recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpClientRoute = McpClientRouteImport.update({
  id: '/mcp/$client',
  path: '/mcp/$client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataCapabilityRoute = ApiDataCapabilityRouteImport.update({
  id: '/api/data/$capability',
  path: '/api/data/$capability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugIndexRoute = ProjectsSlugIndexRouteImport.update({
  id: '/projects/$slug/',
  path: '/projects/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugTopicRoute = ProjectsSlugTopicRouteImport.update({
  id: '/projects/$slug/$topic',
  path: '/projects/$slug/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugThisWeekRoute = ProjectsSlugThisWeekRouteImport.update({
  id: '/projects/$slug/this-week',
  path: '/projects/$slug/this-week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/api/docs': typeof ApiDocsRoute
  '/b/$': typeof BSplatRoute
  '/cookbook/$recipe': typeof CookbookRecipeRoute
  '/mcp/$client': typeof McpClientRoute
  '/api/': typeof ApiIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/api/data/$capability': typeof ApiDataCapabilityRoute
  '/projects/$slug/$topic': typeof ProjectsSlugTopicRoute
  '/projects/$slug/this-week': typeof ProjectsSlugThisWeekRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/api/docs': typeof ApiDocsRoute
  '/b/$': typeof BSplatRoute
  '/cookbook/$recipe': typeof CookbookRecipeRoute
  '/mcp/$client': typeof McpClientRoute
  '/api': typeof ApiIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cookbook': typeof CookbookIndexRoute
  '/mcp': typeof McpIndexRoute
  '/api/data/$capability': typeof ApiDataCapabilityRoute
  '/projects/$slug/$topic': typeof ProjectsSlugTopicRoute
  '/projects/$slug/this-week': typeof ProjectsSlugThisWeekRoute
  '/projects/$slug': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/api/docs': typeof ApiDocsRoute
  '/b/$': typeof BSplatRoute
  '/cookbook/$recipe': typeof CookbookRecipeRoute
  '/mcp/$client': typeof McpClientRoute
  '/api/': typeof ApiIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/api/data/$capability': typeof ApiDataCapabilityRoute
  '/projects/$slug/$topic': typeof ProjectsSlugTopicRoute
  '/projects/$slug/this-week': typeof ProjectsSlugThisWeekRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/dashboards'
    | '/mobile'
    | '/privacy'
    | '/api/docs'
    | '/b/$'
    | '/cookbook/$recipe'
    | '/mcp/$client'
    | '/api/'
    | '/blog/'
    | '/cookbook/'
    | '/mcp/'
    | '/api/data/$capability'
    | '/projects/$slug/$topic'
    | '/projects/$slug/this-week'
    | '/projects/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/dashboards'
    | '/mobile'
    | '/privacy'
    | '/api/docs'
    | '/b/$'
    | '/cookbook/$recipe'
    | '/mcp/$client'
    | '/api'
    | '/blog'
    | '/cookbook'
    | '/mcp'
    | '/api/data/$capability'
    | '/projects/$slug/$topic'
    | '/projects/$slug/this-week'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/dashboards'
    | '/mobile'
    | '/privacy'
    | '/api/docs'
    | '/b/$'
    | '/cookbook/$recipe'
    | '/mcp/$client'
    | '/api/'
    | '/blog/'
    | '/cookbook/'
    | '/mcp/'
    | '/api/data/$capability'
    | '/projects/$slug/$topic'
    | '/projects/$slug/this-week'
    | '/projects/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRoute
  MobileRoute: typeof MobileRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BSplatRoute: typeof BSplatRoute
  CookbookRecipeRoute: typeof CookbookRecipeRoute
  McpClientRoute: typeof McpClientRoute
  ApiIndexRoute: typeof ApiIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  ApiDataCapabilityRoute: typeof ApiDataCapabilityRoute
  ProjectsSlugTopicRoute: typeof ProjectsSlugTopicRoute
  ProjectsSlugThisWeekRoute: typeof ProjectsSlugThisWeekRoute
  ProjectsSlugIndexRoute: typeof ProjectsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$': {
      id: '/b/$'
      path: '/b/$'
      fullPath: '/b/$'
      preLoaderRoute: typeof BSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/cookbook'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/$recipe': {
      id: '/cookbook/$recipe'
      path: '/cookbook/$recipe'
      fullPath: '/cookbook/$recipe'
      preLoaderRoute: typeof CookbookRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$client': {
      id: '/mcp/$client'
      path: '/mcp/$client'
      fullPath: '/mcp/$client'
      preLoaderRoute: typeof McpClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/$capability': {
      id: '/api/data/$capability'
      path: '/api/data/$capability'
      fullPath: '/api/data/$capability'
      preLoaderRoute: typeof ApiDataCapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/': {
      id: '/projects/$slug/'
      path: '/projects/$slug'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof ProjectsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/$topic': {
      id: '/projects/$slug/$topic'
      path: '/projects/$slug/$topic'
      fullPath: '/projects/$slug/$topic'
      preLoaderRoute: typeof ProjectsSlugTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/this-week': {
      id: '/projects/$slug/this-week'
      path: '/projects/$slug/this-week'
      fullPath: '/projects/$slug/this-week'
      preLoaderRoute: typeof ProjectsSlugThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRoute,
  MobileRoute: MobileRoute,
  PrivacyRoute: PrivacyRoute,
  ApiDocsRoute: ApiDocsRoute,
  BSplatRoute: BSplatRoute,
  CookbookRecipeRoute: CookbookRecipeRoute,
  McpClientRoute: McpClientRoute,
  ApiIndexRoute: ApiIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CookbookIndexRoute: CookbookIndexRoute,
  McpIndexRoute: McpIndexRoute,
  ApiDataCapabilityRoute: ApiDataCapabilityRoute,
  ProjectsSlugTopicRoute: ProjectsSlugTopicRoute,
  ProjectsSlugThisWeekRoute: ProjectsSlugThisWeekRoute,
  ProjectsSlugIndexRoute: ProjectsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
